server:
  port: ${KV_SERVER_PORT:8084}

spring:
  application:
    name: xiaolanshu-kv
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        group: DEFAULT_GROUP
