server:
  port: ${USER_SERVER_PORT:8082}

spring:
  application:
    name: xiaolanshu-user
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:true}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        group: DEFAULT_GROUP
